# Generated by Django 5.2.11 on 2026-02-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatconversation_title_set_by_user_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='message_usages',
            field=models.JSONField(blank=True, default=dict, help_text='Extended usage metrics per message ID (tokens, cost, carbon, latency)'),
        ),
    ]
