# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_add_message_usages"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="message_feedbacks",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "User feedback per message ID: "
                    "{message_id: {value: 'positive'|'negative', comment?: string}}"
                ),
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="message_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Sources per message ID: "
                    "{message_id: [{sourceType, id, url, title, providerMetadata}]}"
                ),
            ),
        ),
    ]
