# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_message_feedbacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="message_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Sources per message ID: "
                    "{message_id: [{sourceType, id, url, title, providerMetadata}]}"
                ),
            ),
        ),
    ]
